[env:esp32c3]
platform = espressif32@6.9.0
board = seeed_xiao_esp32c3
framework = arduino
monitor_speed = 115200
lib_deps =
    h2zero/NimBLE-Arduino@^2.1.2
    knolleary/PubSubClient@^2.8
    bblanchon/ArduinoJson@^7.3.0
build_flags =
    -DCONFIG_BT_NIMBLE_ROLE_CENTRAL=1
    -DCONFIG_BT_NIMBLE_ROLE_PERIPHERAL=0
    -DCONFIG_BT_NIMBLE_ROLE_BROADCASTER=0
    -DCONFIG_BT_NIMBLE_ROLE_OBSERVER=1
    -DCONFIG_BT_NIMBLE_MAX_CONNECTIONS=1
